version: "3.8"

services:
    php:
        image: php:8.2-fpm
        container_name: php-fpm
        volumes:
            - .:/var/www/html # 현재 프로젝트 폴더를 PHP 컨테이너에 마운트
        networks:
            - app-network
        depends_on:
            - mysql
        ports:
            - "8000:8000" # PHP 내장 서버를 8000번 포트로 열기
        command: bash -c "docker-php-ext-install pdo_mysql && php -S 0.0.0.0:8000 -t public/" # pdo_mysql 설치 후 PHP 내장 서버 실행

    mysql:
        image: mysql:8.0
        container_name: mysql-db
        environment:
            MYSQL_ROOT_PASSWORD: rootpassword # MySQL root 비밀번호
            MYSQL_DATABASE: udemy_laravel # 초기 데이터베이스 이름
        ports:
            - "3306:3306" # MySQL 외부 접근을 위해 포트 열기
        volumes:
            - mysql-data:/var/lib/mysql # 데이터 영속성을 위해 볼륨 사용
        networks:
            - app-network

# 네트워크 설정
networks:
    app-network:
        driver: bridge

# 데이터 영속성을 위한 볼륨 설정
volumes:
    mysql-data:
